version : '2'
services:

  users-mysql:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    container_name: users-mysql
    links:
      - "mysql-standalone:mysql"

  mysql-standalone:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    container_name: mysql-standalone

